# Thông tin k?t n?i MySQL
spring.datasource.url=jdbc:mysql://localhost:3307/N11NHK_shop?useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=kien120105

# ?Ã ?N DÒNG NÀY ?? S?A L?I "Driver is not assignable" (Spring Boot t? nh?n di?n ???c)
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# C?u hình Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ?Ã ?N DÒNG NÀY ?? TRÁNH C?NH BÁO VÀNG (Hibernate t? ??ng nh?n di?n MySQL Dialect)
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# C?u hình Thymeleaf (T?t cache ?? khi s?a code HTML, ra trình duy?t F5 là ?n ngay)
spring.thymeleaf.cache=false